import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const STORE_LAT = 40.4093;
const STORE_LNG = 49.8671;

const defaultCategories = [
  {
    id: 'cat-mono',
    slug: 'mono-buketler',
    name: 'Mono Buketlər',
    description: 'Tək növ güldən hazırlanmış minimalist buketlər',
    imageUrl: 'https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?w=900&q=80',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-qarisiq',
    slug: 'qarisiq-buketler',
    name: 'Qarışıq Buketlər',
    description: 'Müxtəlif güllərin uyğun birləşməsindən yaranan buketlər',
    imageUrl: 'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?w=900&q=80',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-premium',
    slug: 'premium-kompozisiyalar',
    name: 'Premium Kompozisiya və Buketlər',
    description: 'Seçilmiş premium güllərdən hazırlanmış lüks kompozisiyalar',
    imageUrl: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?w=900&q=80',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-sebet',
    slug: 'sebet-qutu-kompozisiyalar',
    name: 'Səbət və Qutuda Kompozisiyalar',
    description: 'Səbət və xüsusi qutu içində təqdim olunan gül kompozisiyaları',
    imageUrl: 'https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=900&q=80',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'cat-gelin',
    slug: 'gelin-buketleri',
    name: 'Gəlin Buketləri',
    description: 'Toy mərasimləri üçün xüsusi hazırlanmış gəlin buketləri',
    imageUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=900&q=80',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'cat-art',
    slug: 'art',
    name: 'Art',
    description: 'Floristik sənət əsərləri — klassik çərçivədən kənara çıxan kompozisiyalar',
    imageUrl: 'https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=900&q=80',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'cat-newborn',
    slug: 'yeni-dogulmus',
    name: 'Yeni Doğulmuş Uşaq Çıxışı',
    description: 'Yeni doğulan uşaq üçün xüsusi hazırlanmış zərif buket və kompozisiyalar',
    imageUrl: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=900&q=80',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'cat-yeni-il',
    slug: 'yeni-il-kompozisiyalari',
    name: 'Yeni İl Kompozisiyaları',
    description: 'Yeni il və qış mövsümü üçün xüsusi dekorlu çiçək kompozisiyaları',
    imageUrl: 'https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=900&q=80',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'cat-novruz',
    slug: 'novruz',
    name: 'Novruz',
    description: 'Novruz bayramı ruhunu əks etdirən milli koloritli gül kompozisiyaları',
    imageUrl: 'https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?w=900&q=80',
    sortOrder: 9,
    isActive: true,
  },
  {
    id: 'cat-dekor',
    slug: 'toy-ad-guunu-nisar-dekor',
    name: 'Toy, Ad günü, Nişan və Nigar Dekorları',
    description: 'Xüsusi tədbirlər üçün tam məkan bəzəyi və dekor həlləri',
    imageUrl: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=900&q=80',
    sortOrder: 10,
    isActive: true,
  },
];

const defaultZones = [
  {
    id: 'zone-baku-center',
    name: '0–3 km',
    centerLat: STORE_LAT,
    centerLng: STORE_LNG,
    radiusKm: 3,
    deliveryFee: 5,
    color: '#4ade80',
    isActive: true,
  },
  {
    id: 'zone-baku-north',
    name: '3–7 km',
    centerLat: STORE_LAT,
    centerLng: STORE_LNG,
    radiusKm: 7,
    deliveryFee: 7,
    color: '#86efac',
    isActive: true,
  },
  {
    id: 'zone-baku-ring-3',
    name: '7–10 km',
    centerLat: STORE_LAT,
    centerLng: STORE_LNG,
    radiusKm: 10,
    deliveryFee: 10,
    color: '#fbbf24',
    isActive: true,
  },
  {
    id: 'zone-baku-ring-4',
    name: '10–15 km',
    centerLat: STORE_LAT,
    centerLng: STORE_LNG,
    radiusKm: 15,
    deliveryFee: 15,
    color: '#fb923c',
    isActive: true,
  },
  {
    id: 'zone-baku-ring-5',
    name: '15–20 km',
    centerLat: STORE_LAT,
    centerLng: STORE_LNG,
    radiusKm: 20,
    deliveryFee: 20,
    color: '#f87171',
    isActive: true,
  },
] as const;

async function main() {
  for (const cat of defaultCategories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    });
  }

  // Delete all existing products before re-seeding (clear dependents first)
  await prisma.orderItem.deleteMany({});
  await prisma.product.deleteMany({});

  await prisma.product.createMany({
    data: [
      {
        id: 'prod-01',
        slug: 'qirmizi-gullu-orxideyali-buket',
        name: 'Qırmızı Gül və Orxideya Buketi',
        subtitle: 'Qırmızı qızılgül, ağ ortanca və çəhrayı orxideya',
        stemNote: 'Romantik tədbirlər üçün ideal seçim',
        price: 89,
        imageUrl: '/uploads/products/product-01.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-02',
        slug: 'seftali-premium-buket',
        name: 'Şəftali Rəngli Premium Buket',
        subtitle: 'Şəftali qızılgül, orxideya, delphin və ağ ortanca',
        stemNote: 'Premium hədiyyə üçün mükəmməl kompozisiya',
        price: 120,
        imageUrl: '/uploads/products/product-02.jpg',
        category: 'Premium Kompozisiya və Buketlər',
        categorySlug: 'premium-kompozisiyalar',
      },
      {
        id: 'prod-03',
        slug: 'krem-gul-gelin-buketi',
        name: 'Krem Gül Gəlin Buketi',
        subtitle: 'Krem qızılgül, ağ ortanca və zərif gipsofila',
        stemNote: 'Toy mərasimi üçün klassik gəlin buketi',
        price: 95,
        imageUrl: '/uploads/products/product-03.jpg',
        category: 'Gəlin Buketləri',
        categorySlug: 'gelin-buketleri',
      },
      {
        id: 'prod-04',
        slug: 'cehrayi-pion-gul-buketi',
        name: 'Çəhrayı Pion Qızılgül Buketi',
        subtitle: 'Solğun çəhrayı pion tipli qızılgüllər',
        stemNote: 'Ad günü və sevgi ifadəsi üçün',
        price: 75,
        imageUrl: '/uploads/products/product-04.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-05',
        slug: 'benovsheyi-yasemin-buketi',
        name: 'Bənövşəyi Yasəmən Buketi',
        subtitle: 'Təzə bənövşəyi yasəmən çiçəkləri',
        stemNote: 'Bahar mövsümünün ən populyar hədiyyəsi',
        price: 55,
        imageUrl: '/uploads/products/product-05.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-06',
        slug: 'yasemin-sebeti',
        name: 'Yasəmən Səbəti',
        subtitle: 'Hörülmüş səbətdə bənövşəyi yasəmən',
        stemNote: 'Romantik açıq hava hədiyyəsi',
        price: 68,
        imageUrl: '/uploads/products/product-06.jpg',
        category: 'Səbət və Qutuda Kompozisiyalar',
        categorySlug: 'sebet-qutu-kompozisiyalar',
      },
      {
        id: 'prod-07',
        slug: 'ag-pion-gul-buketi',
        name: 'Ağ Pion Qızılgül Buketi',
        subtitle: 'Böyük ağ pion tipli qızılgüllər',
        stemNote: 'Lüks görünüş üçün mono buket',
        price: 110,
        imageUrl: '/uploads/products/product-07.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-08',
        slug: 'cehrayi-krem-qarisiq-buket',
        name: 'Çəhrayı-Krem Qarışıq Buket',
        subtitle: 'Çəhrayı ortanca, krem qızılgül, delphin və mavi vurğular',
        stemNote: 'Sevgi və diqqət üçün rəngarəng seçim',
        price: 98,
        imageUrl: '/uploads/products/product-08.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-09',
        slug: 'benovsheyi-sebet-kompozisiya',
        name: 'Bənövşəyi Səbət Kompozisiyası',
        subtitle: 'Bənövşəyi tonlarda ortanca, qızılgül, orxideya və delphin',
        stemNote: 'Böyük tədbirlər üçün görünüşlü kompozisiya',
        price: 145,
        imageUrl: '/uploads/products/product-09.jpg',
        category: 'Səbət və Qutuda Kompozisiyalar',
        categorySlug: 'sebet-qutu-kompozisiyalar',
      },
      {
        id: 'prod-10',
        slug: 'ag-zanbaq-qarisiq-buket',
        name: 'Ağ Zanbaq Qarışıq Buketi',
        subtitle: 'Ağ zanbaq, anturium, qərənfil və yaşıl vurğular',
        stemNote: 'Təziyə və rəsmi tədbirlər üçün',
        price: 72,
        imageUrl: '/uploads/products/product-10.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-11',
        slug: 'taurus-qutu-kompozisiya',
        name: 'Taurus Qutu Kompozisiyası',
        subtitle: 'Çəhrayı ortanca, qızılgül, anturium və özel Taurus qutusu',
        stemNote: 'Bürc temali unikal hədiyyə kompozisiyası',
        price: 135,
        imageUrl: '/uploads/products/product-11.jpg',
        category: 'Art',
        categorySlug: 'art',
      },
      {
        id: 'prod-12',
        slug: 'mavi-ag-buket',
        name: 'Mavi-Ağ Buket',
        subtitle: 'Krem qızılgül, ağ ortanca və mavi delphin',
        stemNote: 'Kişi hədiyyəsi üçün unikal rəng kombinasiyası',
        price: 85,
        imageUrl: '/uploads/products/product-12.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-13',
        slug: 'yasemin-krem-gul-buket',
        name: 'Yasəmən və Krem Qızılgül Buketi',
        subtitle: 'Bənövşəyi yasəmən və krem pion qızılgülü',
        stemNote: 'Bahar ruhunu daşıyan qarışıq buket',
        price: 78,
        imageUrl: '/uploads/products/product-13.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-14',
        slug: 'cehrayi-ranunkulus-buket',
        name: 'Çəhrayı Ranunkulus Buketi',
        subtitle: 'Çəhrayı ranunkulus, ağ ortanca, çəhrayı qızılgül və papatya',
        stemNote: 'Yumşaq və romantik görünüş',
        price: 65,
        imageUrl: '/uploads/products/product-14.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
      {
        id: 'prod-15',
        slug: 'ranunkulus-mono-buket',
        name: 'Ranunkulus Mono Buketi',
        subtitle: 'Çəhrayı və ağ ranunkulus çiçəkləri',
        stemNote: 'Zərif və incə mono buket',
        price: 88,
        imageUrl: '/uploads/products/product-15.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-16',
        slug: 'taurus-ag-kompozisiya',
        name: 'Taurus Ağ Kompozisiya',
        subtitle: 'Ağ ortanca, qızılgül, zəng çiçəkləri və anturium',
        stemNote: 'Bürc temali premium art kompozisiya',
        price: 160,
        imageUrl: '/uploads/products/product-16.jpg',
        category: 'Art',
        categorySlug: 'art',
      },
      {
        id: 'prod-17',
        slug: 'cehrayi-pion-mono-buket',
        name: 'Çəhrayı Pion Mono Buketi',
        subtitle: 'Solğun çəhrayı pion çiçəkləri',
        stemNote: 'Böyük və vüqarlı mono pion buketi',
        price: 130,
        imageUrl: '/uploads/products/product-17.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-18',
        slug: 'parlaq-cehrayi-gul-buketi',
        name: 'Parlaq Çəhrayı Qızılgül Buketi',
        subtitle: 'Canlı çəhrayı rəngli pion qızılgüllər',
        stemNote: 'Enerjili və şən hədiyyə üçün',
        price: 92,
        imageUrl: '/uploads/products/product-18.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-19',
        slug: 'seftali-pion-gul-mono',
        name: 'Şəftali Pion Qızılgül Mono',
        subtitle: 'Şəftali-çəhrayı pion tipli qızılgüllər',
        stemNote: 'Nəzakətli və zərif mono buket',
        price: 85,
        imageUrl: '/uploads/products/product-19.jpg',
        category: 'Mono Buketlər',
        categorySlug: 'mono-buketler',
      },
      {
        id: 'prod-20',
        slug: 'qirmizi-cehrayi-ortanca-buket',
        name: 'Qırmızı-Çəhrayı Qızılgül və Ortanca',
        subtitle: 'Qırmızı pion qızılgül, solğun çəhrayı qızılgül və çəhrayı ortanca',
        stemNote: 'Eşq etirafı üçün güclü rəng kompozisiyası',
        price: 105,
        imageUrl: '/uploads/products/product-20.jpg',
        category: 'Qarışıq Buketlər',
        categorySlug: 'qarisiq-buketler',
      },
    ],
  });

  for (const zone of defaultZones) {
    await prisma.zone.upsert({
      where: { id: zone.id },
      update: zone,
      create: zone,
    });
  }

  console.log('Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
