import { Product } from '@/entities/product/types';

const FLOWER_GALLERY_POOL = [
  '/images/products/ivory-hydrangea.png',
  '/images/products/ranunculus-candlelight.png',
  '/images/products/morning-rose-box.png',
  '/images/products/pastel-tulip-cloud.png',
  '/images/products/olive-white-bouquet.png',
  '/images/products/dinner-mini.png',
  '/images/products/peony-bouquet.png',
  '/images/products/rose-crown.png',
  '/images/products/mint-wildflower.png',
  '/images/products/dried-pampas.png',
  '/images/studio/gallery-1.png',
  '/images/studio/gallery-2.png',
  '/images/studio/gallery-3.png',
  '/images/studio/gallery-4.png',
];

function withGalleryImages(products: Product[]): Product[] {
  return products.map((product, index) => ({
    ...product,
    galleryImages: [
      product.imageUrl,
      FLOWER_GALLERY_POOL[(index + 1) % FLOWER_GALLERY_POOL.length],
      FLOWER_GALLERY_POOL[(index + 2) % FLOWER_GALLERY_POOL.length],
    ],
  }));
}

export const SEED_PRODUCTS: Product[] = withGalleryImages([
  {
    id: '5',
    slug: 'ivory-hydrangea',
    name: 'Krem Ortanca Kompozisiyası',
    subtitle: 'Ortanca, lisianthus və açıq zeytun yarpaqları',
    stemNote: 'Masa üstü və giriş konsolu üçün ideal',
    price: 74,
    imageUrl: '/images/products/ivory-hydrangea.png',
    category: 'Kompozisiya',
    categorySlug: 'premium-kompozisiyalar',
  },
  {
    id: '6',
    slug: 'ranunculus-candlelight',
    name: 'Şam Nuru Ranunkulus',
    subtitle: 'Şaftalı və pudra tonlarında sıx ranunkulus qatları',
    stemNote: 'Axşam süfrələri üçün yumşaq parlaqlıq',
    price: 59,
    imageUrl: '/images/products/ranunculus-candlelight.png',
    category: 'Buket',
    categorySlug: 'qarisiq-buketler',
  },
  {
    id: '7',
    slug: 'morning-rose-box',
    name: 'Səhər Bağı Gül Qutusu',
    subtitle: 'Qutu içində yığılmış bağ gülləri və qaymaq lent detalı',
    stemNote: 'Otel qarşılama və hədiyyə təqdimatı üçün',
    price: 82,
    imageUrl: '/images/products/morning-rose-box.png',
    category: 'Qutu',
    categorySlug: 'sebet-qutu-kompozisiyalar',
  },
  {
    id: '8',
    slug: 'pastel-tulip-cloud',
    name: 'Pastel Lalə Buludu',
    subtitle: 'Lalə, freziya və ipək kimi açılan yaz tonları',
    stemNote: 'Səhər çatdırılması üçün ən çox seçilənlərdən',
    price: 42,
    imageUrl: '/images/products/pastel-tulip-cloud.png',
    category: 'Yaz',
    categorySlug: 'yeni-dogulmus',
  },
  {
    id: '9',
    slug: 'olive-white-bouquet',
    name: 'Zeytun Yarpaqlı Ağ Buket',
    subtitle: 'Ağ qızılgül, anturium və zeytun yarpaqlı təmiz siluet',
    stemNote: 'Minimal interyerlər üçün sakit seçim',
    price: 77,
    imageUrl: '/images/products/olive-white-bouquet.png',
    category: 'Ağ Ton',
    categorySlug: 'toy-ad-guunu-nisar-dekor',
  },
  {
    id: '10',
    slug: 'dinner-mini-arrangement',
    name: 'Axşam Süfrəsi Mini Aranjman',
    subtitle: 'Aşağı boylu masa kompozisiyası və şam işığına uyğun forma',
    stemNote: 'Özəl axşam yeməkləri üçün hazırlanır',
    price: 33,
    imageUrl: '/images/products/dinner-mini.png',
    category: 'Masa',
    categorySlug: 'yeni-il-kompozisiyalari',
  },
  {
    id: '1',
    slug: 'blushing-peony',
    name: 'Pion Buketi',
    subtitle: 'Toz çəhrayı pionlar, krem tonlu qatlar və atlas lent',
    stemNote: 'Mərkəzi Bakı üzrə eyni gün təqdimat',
    price: 68,
    imageUrl: '/images/products/peony-bouquet.png',
    category: 'Buket',
    categorySlug: 'mono-buketler',
  },
  {
    id: '2',
    slug: 'garden-rose-crown',
    name: 'Bağ Qızılgülü Tacı',
    subtitle: 'Yüngül qızılgül, gipsofila və yumşaq yaşıl vurğular',
    stemNote: 'Foto çəkiliş və nişan səhərləri üçün',
    price: 45,
    imageUrl: '/images/products/rose-crown.png',
    category: 'Tac',
    categorySlug: 'gelin-buketleri',
  },
  {
    id: '3',
    slug: 'mint-wildflower',
    name: 'Nanəli Çiçək Dəstəsi',
    subtitle: 'Vəhşi çiçəklər, nanə tonu və sərbəst bağlanmış forma',
    stemNote: 'Sakit təşəkkür jesti üçün seçilir',
    price: 38,
    imageUrl: '/images/products/mint-wildflower.png',
    category: 'Dəstə',
    categorySlug: 'novruz',
  },
  {
    id: '4',
    slug: 'dried-pampas',
    name: 'Qurudulmuş Pampas və Gül',
    subtitle: 'Uzunömürlü pampas, qurudulmuş qızılgül və lunaria',
    stemNote: 'Məkan üçün qalıcı kompozisiya',
    price: 55,
    imageUrl: '/images/products/dried-pampas.png',
    category: 'Quru',
    categorySlug: 'art',
  },
]);
